pypi_metrics:
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      threads: 1
    prod:
      type: duckdb
      path: "md:{{ env_var('DATABASE_NAME', 'duckdb_stats') }}"
      threads: 1
  target: dev
